### ISSUE TITLE
[bug] CSS not updating with HMR

### ISSUE THREAD

**Issue by lnfnunes** [luangjokaj/react-fondue#10]
Looks like HMR is not working for .css files!
I've changed file `src/Components/Nav/Nav.css` and the browser's console identified the change as you can see in the image:
![image](https://user-images.githubusercontent.com/2450417/51488841-cd17e400-1d8d-11e9-97bc-271b34ca112c.png)

But the change only get in place when I do a full reload on browser

**Comment by luangjokaj** [comment]
Hey @lnfnunes thank you for your feedback. It's actually still an open issue of the **mini-css-extract-plugin** package https://github.com/webpack-contrib/mini-css-extract-plugin/issues/34

But you are right, this is very annoying. I switched the default client development configuration to use `style-loader` instead. This will allow the support of HMR for CSS. And it's not a deal breaker because `mini-css-extract-plugin` will work just fine in production.

I pushed this already ccfb73682f1127bd92a0ffee42ee4e2cacc7fdcf.
Let me know if this fixes your issue.

**Comment by lnfnunes** [comment]
Thank you so much! Appreciate the _fast-reply_ ;-)

**Comment by lnfnunes** [comment]
@luangjokaj Just to know, why keep production different? Isn't better to change both and prevent future diferrences?

**Comment by luangjokaj** [comment]
Because we inject dynamically only what we use. 
[mini-css-extract-plugin](https://github.com/webpack-contrib/mini-css-extract-plugin)
```This plugin extracts CSS into separate files. It creates a CSS file per JS file which contains CSS. It supports On-Demand-Loading of CSS and SourceMaps.```

**Comment by luangjokaj** [comment]
I switched to `MiniCssExtractPlugin` in development. This will fix the initial flashing.
