### ISSUE TITLE
support  external css issue

### ISSUE THREAD

**Issue by webexpert4rv** [luangjokaj/react-fondue#20]
#css is not imported in component

import 'style.css'
class ABC extends component{
render(){
   return(
              <div className="test-css">dawdawd</div>
         )
  }
}

not reflecting CSS property.
How to add CSS in the component. and only want to load that component CSS not other components.

**Comment by luangjokaj** [comment]
We are using css modules. You can import the css as shown also here:
https://github.com/luangjokaj/react-fondue/blob/master/src/App/Routes.js

On line 10: `import '../assets/css/styles.css';`

But you need to add everything in `:global` in order to be accessible outside of CSS modules.
https://github.com/css-modules/css-modules#exceptions
